# Generated by Django 5.1.6 on 2025-02-12 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0003_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Musician',
        ),
    ]
